### ISSUE TITLE
Release Workflow

### ISSUE THREAD

**Issue by ppussar** [semantic-gitlog/gradle-semantic-gitlog#5]
Hi, 
I'm playing with this plugin. I am wondering how to create a changelog for a certain release.
When I am using `./gradlew changelog` I can nicely create a changelog till my latest tag, which is my last release, e.g. 1.1.0

However I want to create the changelog for my new release with version 1.2.0. The generated changelog should be part of the tagged commit. How can I achive this?

Or same question asked differend: What is your workflow (with commands) to release this project?

Thanks,
Patrick

**Comment by ococl** [comment]
First of all, I didn't understand you for a while. Let me try to answer that.

Q1:
There has no build-in support for generate changelog of single tag, you can do this by modifying the template.
I can provide it in subsequent updates.

Q2:
I've tried using workflows to automatically generate changelogs(see https://github.com/semantic-gitlog/semantic-gitlog/blob/d09195a560/.travis/deploy-release.sh#L39), but some problems have been encountered.

When I pushback the generated CHANGELOG.md to git(hub), the relevant commit ID(hash) has changed.This leads to mess of commit history and tags, and there is no way I can solve it.

And now, I use the following solution:
1. use gradle(or kotlin gradle) script generate changelog and bump project version field to new version value;
2. commit and push code to git;
3. CI will run and publish the package(as usual);

Here's my script in a project that you can refer to:
```kotlin
tasks.register("bumpVersion") {
    // invoke changelog task to generate the changelog and derive the new version.
    dependsOn(":changelog")

    doLast {
        var newVersion = rootProject.findProperty("newVersion") as? String

        if (newVersion.isNullOrEmpty()) {
            // ^## ([\d\.]+(-SNAPSHOT)?) \(.+\)$
            val changelogContents = file("${rootProject.rootDir}/CHANGELOG.md").readText()
            val versionRegex = Regex("^## ([\\d\\.]+(-SNAPSHOT)?) \\(.+\\)\$", setOf(RegexOption.MULTILINE))
            val changelogVersion = versionRegex.find(changelogContents)?.groupValues?.get(1)

            changelogVersion?.let { newVersion = it }

            logger.warn("changelogVersion: {}", changelogVersion)
            logger.warn("newVersion: {}", newVersion)
        }

        newVersion?.let {
            logger.info("Set Project to new Version $it")

            val contents = buildFile.readText()
                // .replaceFirst("version = \"$version\"", "version = \"$newVersion\"")
                // const val emtbootVersion = "0.7.0-SNAPSHOT"
                .replaceFirst("const val emtbootVersion = \"$version\"", "const val emtbootVersion = \"$it\"")

            buildFile.writeText(contents)
        }
    }
}
```
