### ISSUE TITLE
Missing commits in the change log

### ISSUE THREAD

**Issue by kalap92** [semantic-gitlog/gradle-semantic-gitlog#6]
I have created a dummy repo:

https://github.com/kalap92/kalap-test

As you can see there are some commits on the repo however in the changelog https://github.com/kalap92/kalap-test/blob/master/CHANGELOG.md generated by your plugin (as you can see in build.gradle) I can only see "No update notes".

Is iterating over commits not working properly?

**Comment by ococl** [comment]
Because there are no compliant commit messages in your repository. 

See: https://www.conventionalcommits.org/en/v1.0.0/
